/*
 * OITExpansionBoardDefines.h
 *
 * Created: 04/09/20 2:20:16 PM
 *  Author: troy
 *  		EXT1			EXT3
 * 1	PIO_PB2_IDX		PIO_PA17_IDX
 * 2	PIO_PB3_IDX		PIO_PC13_IDX
 * 3	PIO_PA24_IDX	PIO_PD28_IDX
 * 4	PIO_PA25_IDX	PIO_PD17_IDX
 * 5	PIO_PA15_IDX	PIO_PD20_IDX
 * 6	PIO_PA16_IDX	PIO_PD24_IDX
 * 7	PIO_PA11_IDX	PIO_PE1_IDX
 * 8	PIO_PD25_IDX	PIO_PD26_IDX
 * 9	PIO_PB14_IDX	PIO_PD30_IDX
 */ 

#ifndef OITEXPANSIONBOARDDEFINES_H_
#define OITEXPANSIONBOARDDEFINES_H_

#ifdef OIT_LED_FULL_BOARD_EXT1
#define EXT1_LED1_GPIO					(PIO_PB2_IDX)
#define EXT1_LED1_FLAGS					(0)
#define EXT1_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_1_PIN					EXT1_LED1_GPIO
#define EXT1_LED_1_ACTIVE				EXT1_LED1_ACTIVE_LEVEL
#define EXT1_LED_1_INACTIVE				EXT1_LED1_INACTIVE_LEVEL

#define EXT1_LED2_GPIO					(PIO_PB3_IDX)
#define EXT1_LED2_FLAGS					(0)
#define EXT1_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_2_PIN					EXT1_LED2_GPIO
#define EXT1_LED_2_ACTIVE				EXT1_LED2_ACTIVE_LEVEL
#define EXT1_LED_2_INACTIVE				EXT1_LED2_INACTIVE_LEVEL

#define EXT1_LED3_GPIO					(PIO_PA24_IDX)
#define EXT1_LED3_FLAGS					(0)
#define EXT1_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_3_PIN					EXT1_LED3_GPIO
#define EXT1_LED_3_ACTIVE				EXT1_LED3_ACTIVE_LEVEL
#define EXT1_LED_3_INACTIVE				EXT1_LED3_INACTIVE_LEVEL

#define EXT1_LED4_GPIO					(PIO_PA25_IDX)
#define EXT1_LED4_FLAGS					(0)
#define EXT1_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_4_PIN					EXT1_LED4_GPIO
#define EXT1_LED_4_ACTIVE				EXT1_LED4_ACTIVE_LEVEL
#define EXT1_LED_4_INACTIVE				EXT1_LED4_INACTIVE_LEVEL

#define EXT1_LED5_GPIO					(PIO_PA15_IDX)
#define EXT1_LED5_FLAGS					(0)
#define EXT1_LED5_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED5_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_5_PIN					EXT1_LED5_GPIO
#define EXT1_LED_5_ACTIVE				EXT1_LED5_ACTIVE_LEVEL
#define EXT1_LED_5_INACTIVE				EXT1_LED5_INACTIVE_LEVEL

#define EXT1_LED6_GPIO					(PIO_PA16_IDX)
#define EXT1_LED6_FLAGS					(0)
#define EXT1_LED6_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED6_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_6_PIN					EXT1_LED6_GPIO
#define EXT1_LED_6_ACTIVE				EXT1_LED6_ACTIVE_LEVEL
#define EXT1_LED_6_INACTIVE				EXT1_LED6_INACTIVE_LEVEL

#define EXT1_LED7_GPIO					(PIO_PA11_IDX)
#define EXT1_LED7_FLAGS					(0)
#define EXT1_LED7_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED7_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_7_PIN					EXT1_LED7_GPIO
#define EXT1_LED_7_ACTIVE				EXT1_LED7_ACTIVE_LEVEL
#define EXT1_LED_7_INACTIVE				EXT1_LED7_INACTIVE_LEVEL

#define EXT1_LED8_GPIO					(PIO_PD25_IDX)
#define EXT1_LED8_FLAGS					(0)
#define EXT1_LED8_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED8_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_8_PIN					EXT1_LED8_GPIO
#define EXT1_LED_8_ACTIVE				EXT1_LED8_ACTIVE_LEVEL
#define EXT1_LED_8_INACTIVE				EXT1_LED8_INACTIVE_LEVEL

#define EXT1_LED9_GPIO					(PIO_PB14_IDX)
#define EXT1_LED9_FLAGS					(0)
#define EXT1_LED9_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED9_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_9_PIN					EXT1_LED9_GPIO
#define EXT1_LED_9_ACTIVE				EXT1_LED9_ACTIVE_LEVEL
#define EXT1_LED_9_INACTIVE				EXT1_LED9_INACTIVE_LEVEL
#endif //OIT_LED_FULL_BOARD_EXT1

#ifdef OIT_LED_FULL_BOARD_EXT3
#define EXT3_LED1_GPIO					(PIO_PA17_IDX)
#define EXT3_LED1_FLAGS					(0)
#define EXT3_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_1_PIN					EXT3_LED1_GPIO
#define EXT3_LED_1_ACTIVE				EXT3_LED1_ACTIVE_LEVEL
#define EXT3_LED_1_INACTIVE				EXT3_LED1_INACTIVE_LEVEL

#define EXT3_LED2_GPIO					(PIO_PC13_IDX)
#define EXT3_LED2_FLAGS					(0)
#define EXT3_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_2_PIN					EXT3_LED2_GPIO
#define EXT3_LED_2_ACTIVE				EXT3_LED2_ACTIVE_LEVEL
#define EXT3_LED_2_INACTIVE				EXT3_LED2_INACTIVE_LEVEL

#define EXT3_LED3_GPIO					(PIO_PD28_IDX)
#define EXT3_LED3_FLAGS					(0)
#define EXT3_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_3_PIN					EXT3_LED3_GPIO
#define EXT3_LED_3_ACTIVE				EXT3_LED3_ACTIVE_LEVEL
#define EXT3_LED_3_INACTIVE				EXT3_LED3_INACTIVE_LEVEL

#define EXT3_LED4_GPIO					(PIO_PD17_IDX)
#define EXT3_LED4_FLAGS					(0)
#define EXT3_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_4_PIN					EXT3_LED4_GPIO
#define EXT3_LED_4_ACTIVE				EXT3_LED4_ACTIVE_LEVEL
#define EXT3_LED_4_INACTIVE				EXT3_LED4_INACTIVE_LEVEL

#define EXT3_LED5_GPIO					(PIO_PD20_IDX)
#define EXT3_LED5_FLAGS					(0)
#define EXT3_LED5_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED5_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_5_PIN					EXT3_LED5_GPIO
#define EXT3_LED_5_ACTIVE				EXT3_LED5_ACTIVE_LEVEL
#define EXT3_LED_5_INACTIVE				EXT3_LED5_INACTIVE_LEVEL

#define EXT3_LED6_GPIO					(PIO_PD24_IDX)
#define EXT3_LED6_FLAGS					(0)
#define EXT3_LED6_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED6_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_6_PIN					EXT3_LED6_GPIO
#define EXT3_LED_6_ACTIVE				EXT3_LED6_ACTIVE_LEVEL
#define EXT3_LED_6_INACTIVE				EXT3_LED6_INACTIVE_LEVEL

#define EXT3_LED7_GPIO					(PIO_PE1_IDX)
#define EXT3_LED7_FLAGS					(0)
#define EXT3_LED7_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED7_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_7_PIN					EXT3_LED7_GPIO
#define EXT3_LED_7_ACTIVE				EXT3_LED7_ACTIVE_LEVEL
#define EXT3_LED_7_INACTIVE				EXT3_LED7_INACTIVE_LEVEL

#define EXT3_LED8_GPIO					(PIO_PD26_IDX)
#define EXT3_LED8_FLAGS					(0)
#define EXT3_LED8_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED8_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_8_PIN					EXT3_LED8_GPIO
#define EXT3_LED_8_ACTIVE				EXT3_LED8_ACTIVE_LEVEL
#define EXT3_LED_8_INACTIVE				EXT3_LED8_INACTIVE_LEVEL

#define EXT3_LED9_GPIO					(PIO_PD30_IDX)
#define EXT3_LED9_FLAGS					(0)
#define EXT3_LED9_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED9_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_9_PIN					EXT3_LED9_GPIO
#define EXT3_LED_9_ACTIVE				EXT3_LED9_ACTIVE_LEVEL
#define EXT3_LED_9_INACTIVE				EXT3_LED9_INACTIVE_LEVEL
#endif //OIT_LED_FULL_BOARD_EXT3

#ifdef OIT_BTN_FULL_BOARD_EXT1
#define EXT1_PUSH_BUTTON_1				(PIO_PB2_IDX)
#define EXT1_PUSH_BUTTON_1_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_1_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_2				(PIO_PB3_IDX)
#define EXT1_PUSH_BUTTON_2_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_2_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_3				(PIO_PA24_IDX)
#define EXT1_PUSH_BUTTON_3_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_3_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_4				(PIO_PA25_IDX)
#define EXT1_PUSH_BUTTON_4_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_4_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_5				(PIO_PA15_IDX)
#define EXT1_PUSH_BUTTON_5_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_5_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_6				(PIO_PA16_IDX)
#define EXT1_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_7				(PIO_PA11_IDX)
#define EXT1_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_8				(PIO_PD25_IDX)
#define EXT1_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_9				(PIO_PB14_IDX)
#define EXT1_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_BTN_FULL_BOARD_EXT1

#ifdef OIT_BTN_FULL_BOARD_EXT3
#define EXT3_PUSH_BUTTON_1				(PIO_PA17_IDX)
#define EXT3_PUSH_BUTTON_1_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_1_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_2				(PIO_PC13_IDX)
#define EXT3_PUSH_BUTTON_2_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_2_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_3				(PIO_PD28_IDX)
#define EXT3_PUSH_BUTTON_3_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_3_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_4				(PIO_PD17_IDX)
#define EXT3_PUSH_BUTTON_4_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_4_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_5				(PIO_PD20_IDX)
#define EXT3_PUSH_BUTTON_5_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_5_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_6				(PIO_PD24_IDX)
#define EXT3_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_7				(PIO_PE1_IDX)
#define EXT3_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_8				(PIO_PD26_IDX)
#define EXT3_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_9				(PIO_PD30_IDX)
#define EXT3_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_BTN_FULL_BOARD_EXT3

#ifdef OIT_5LED_4BTN_BOARD_EXT1
#define EXT1_LED1_GPIO					(PIO_PB2_IDX)
#define EXT1_LED1_FLAGS					(0)
#define EXT1_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_1_PIN					EXT1_LED1_GPIO
#define EXT1_LED_1_ACTIVE				EXT1_LED1_ACTIVE_LEVEL
#define EXT1_LED_1_INACTIVE				EXT1_LED1_INACTIVE_LEVEL

#define EXT1_LED2_GPIO					(PIO_PB3_IDX)
#define EXT1_LED2_FLAGS					(0)
#define EXT1_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_2_PIN					EXT1_LED2_GPIO
#define EXT1_LED_2_ACTIVE				EXT1_LED2_ACTIVE_LEVEL
#define EXT1_LED_2_INACTIVE				EXT1_LED2_INACTIVE_LEVEL

#define EXT1_LED3_GPIO					(PIO_PA24_IDX)
#define EXT1_LED3_FLAGS					(0)
#define EXT1_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_3_PIN					EXT1_LED3_GPIO
#define EXT1_LED_3_ACTIVE				EXT1_LED3_ACTIVE_LEVEL
#define EXT1_LED_3_INACTIVE				EXT1_LED3_INACTIVE_LEVEL

#define EXT1_LED4_GPIO					(PIO_PA25_IDX)
#define EXT1_LED4_FLAGS					(0)
#define EXT1_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_4_PIN					EXT1_LED4_GPIO
#define EXT1_LED_4_ACTIVE				EXT1_LED4_ACTIVE_LEVEL
#define EXT1_LED_4_INACTIVE				EXT1_LED4_INACTIVE_LEVEL

#define EXT1_LED5_GPIO					(PIO_PA15_IDX)
#define EXT1_LED5_FLAGS					(0)
#define EXT1_LED5_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED5_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_5_PIN					EXT1_LED5_GPIO
#define EXT1_LED_5_ACTIVE				EXT1_LED5_ACTIVE_LEVEL
#define EXT1_LED_5_INACTIVE				EXT1_LED5_INACTIVE_LEVEL

#define EXT1_PUSH_BUTTON_6				(PIO_PA16_IDX)
#define EXT1_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_7				(PIO_PA11_IDX)
#define EXT1_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_8				(PIO_PD25_IDX)
#define EXT1_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_9				(PIO_PB14_IDX)
#define EXT1_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_5LED_4BTN_BOARD_EXT1

#ifdef OIT_5LED_4BTN_BOARD_EXT3
#define EXT3_LED1_GPIO					(PIO_PA17_IDX)
#define EXT3_LED1_FLAGS					(0)
#define EXT3_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_1_PIN					EXT3_LED1_GPIO
#define EXT3_LED_1_ACTIVE				EXT3_LED1_ACTIVE_LEVEL
#define EXT3_LED_1_INACTIVE				EXT3_LED1_INACTIVE_LEVEL

#define EXT3_LED2_GPIO					(PIO_PC13_IDX)
#define EXT3_LED2_FLAGS					(0)
#define EXT3_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_2_PIN					EXT3_LED2_GPIO
#define EXT3_LED_2_ACTIVE				EXT3_LED2_ACTIVE_LEVEL
#define EXT3_LED_2_INACTIVE				EXT3_LED2_INACTIVE_LEVEL

#define EXT3_LED3_GPIO					(PIO_PD28_IDX)
#define EXT3_LED3_FLAGS					(0)
#define EXT3_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_3_PIN					EXT3_LED3_GPIO
#define EXT3_LED_3_ACTIVE				EXT3_LED3_ACTIVE_LEVEL
#define EXT3_LED_3_INACTIVE				EXT3_LED3_INACTIVE_LEVEL

#define EXT3_LED4_GPIO					(PIO_PD17_IDX)
#define EXT3_LED4_FLAGS					(0)
#define EXT3_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_4_PIN					EXT3_LED4_GPIO
#define EXT3_LED_4_ACTIVE				EXT3_LED4_ACTIVE_LEVEL
#define EXT3_LED_4_INACTIVE				EXT3_LED4_INACTIVE_LEVEL

#define EXT3_LED5_GPIO					(PIO_PD20_IDX)
#define EXT3_LED5_FLAGS					(0)
#define EXT3_LED5_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED5_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_5_PIN					EXT3_LED5_GPIO
#define EXT3_LED_5_ACTIVE				EXT3_LED5_ACTIVE_LEVEL
#define EXT3_LED_5_INACTIVE				EXT3_LED5_INACTIVE_LEVEL

#define EXT3_PUSH_BUTTON_6				(PIO_PD24_IDX)
#define EXT3_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_7				(PIO_PE1_IDX)
#define EXT3_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_8				(PIO_PD26_IDX)
#define EXT3_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT3_PUSH_BUTTON_9				(PIO_PD30_IDX)
#define EXT3_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT3_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_5LED_4BTN_BOARD_EXT3

#ifdef OIT_4LED_5BTN_BOARD_EXT1
#define EXT1_LED1_GPIO					(PIO_PB2_IDX)
#define EXT1_LED1_FLAGS					(0)
#define EXT1_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_1_PIN					EXT1_LED1_GPIO
#define EXT1_LED_1_ACTIVE				EXT1_LED1_ACTIVE_LEVEL
#define EXT1_LED_1_INACTIVE				EXT1_LED1_INACTIVE_LEVEL

#define EXT1_LED2_GPIO					(PIO_PB3_IDX)
#define EXT1_LED2_FLAGS					(0)
#define EXT1_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_2_PIN					EXT1_LED2_GPIO
#define EXT1_LED_2_ACTIVE				EXT1_LED2_ACTIVE_LEVEL
#define EXT1_LED_2_INACTIVE				EXT1_LED2_INACTIVE_LEVEL

#define EXT1_LED3_GPIO					(PIO_PA24_IDX)
#define EXT1_LED3_FLAGS					(0)
#define EXT1_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_3_PIN					EXT1_LED3_GPIO
#define EXT1_LED_3_ACTIVE				EXT1_LED3_ACTIVE_LEVEL
#define EXT1_LED_3_INACTIVE				EXT1_LED3_INACTIVE_LEVEL

#define EXT1_LED4_GPIO					(PIO_PA25_IDX)
#define EXT1_LED4_FLAGS					(0)
#define EXT1_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_4_PIN					EXT1_LED4_GPIO
#define EXT1_LED_4_ACTIVE				EXT1_LED4_ACTIVE_LEVEL
#define EXT1_LED_4_INACTIVE				EXT1_LED4_INACTIVE_LEVEL

#define EXT1_PUSH_BUTTON_5				(PIO_PA15_IDX)
#define EXT1_PUSH_BUTTON_5_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_5_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_6				(PIO_PA16_IDX)
#define EXT1_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_7				(PIO_PA11_IDX)
#define EXT1_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_8				(PIO_PD25_IDX)
#define EXT1_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_9				(PIO_PB14_IDX)
#define EXT1_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_4LED_5BTN_BOARD_EXT1

#ifdef OIT_4LED_5BTN_BOARD_EXT3
#define EXT3_LED1_GPIO					(PIO_PA17_IDX)
#define EXT3_LED1_FLAGS					(0)
#define EXT3_LED1_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED1_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_1_PIN					EXT3_LED1_GPIO
#define EXT3_LED_1_ACTIVE				EXT3_LED1_ACTIVE_LEVEL
#define EXT3_LED_1_INACTIVE				EXT3_LED1_INACTIVE_LEVEL

#define EXT3_LED2_GPIO					(PIO_PC13_IDX)
#define EXT3_LED2_FLAGS					(0)
#define EXT3_LED2_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED2_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_2_PIN					EXT3_LED2_GPIO
#define EXT3_LED_2_ACTIVE				EXT3_LED2_ACTIVE_LEVEL
#define EXT3_LED_2_INACTIVE				EXT3_LED2_INACTIVE_LEVEL

#define EXT3_LED3_GPIO					(PIO_PD28_IDX)
#define EXT3_LED3_FLAGS					(0)
#define EXT3_LED3_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED3_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_3_PIN					EXT3_LED3_GPIO
#define EXT3_LED_3_ACTIVE				EXT3_LED3_ACTIVE_LEVEL
#define EXT3_LED_3_INACTIVE				EXT3_LED3_INACTIVE_LEVEL

#define EXT3_LED4_GPIO					(PIO_PD17_IDX)
#define EXT3_LED4_FLAGS					(0)
#define EXT3_LED4_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT3_LED4_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT3_LED_4_PIN					EXT3_LED4_GPIO
#define EXT3_LED_4_ACTIVE				EXT3_LED4_ACTIVE_LEVEL
#define EXT3_LED_4_INACTIVE				EXT3_LED4_INACTIVE_LEVEL

#define EXT1_LED5_GPIO					(PIO_PA15_IDX)
#define EXT1_LED5_FLAGS					(0)
#define EXT1_LED5_ACTIVE_LEVEL			(IOPORT_PIN_LEVEL_HIGH)
#define EXT1_LED5_INACTIVE_LEVEL		(IOPORT_PIN_LEVEL_LOW)

#define EXT1_LED_5_PIN					EXT1_LED5_GPIO
#define EXT1_LED_5_ACTIVE				EXT1_LED5_ACTIVE_LEVEL
#define EXT1_LED_5_INACTIVE				EXT1_LED5_INACTIVE_LEVEL

#define EXT1_PUSH_BUTTON_6				(PIO_PA16_IDX)
#define EXT1_PUSH_BUTTON_6_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_6_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_7				(PIO_PA11_IDX)
#define EXT1_PUSH_BUTTON_7_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_7_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_8				(PIO_PD25_IDX)
#define EXT1_PUSH_BUTTON_8_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_8_SENSE		(IOPORT_SENSE_RISING)

#define EXT1_PUSH_BUTTON_9				(PIO_PB14_IDX)
#define EXT1_PUSH_BUTTON_9_FLAGS		(IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define EXT1_PUSH_BUTTON_9_SENSE		(IOPORT_SENSE_RISING)
#endif //OIT_4LED_5BTN_BOARD_EXT3

#endif /* OITEXPANSIONBOARDDEFINES_H_ */